accounts/urls.py
# from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"
urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField("email address", unique=True)

    followings = models.ManyToManyField(
        "self",
        related_name="followers",
        through="FriendShip",
        through_fields=("follower", "following"),
        symmetrical=False,
    )


class FriendShip(models.Model):
    follower = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="follower_friendships", on_delete=models.CASCADE
    )
    following = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="following_friendships", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [models.UniqueConstraint(fields=["follower", "following"], name="unique_friendship")]

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

User = get_user_model()


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs["placeholder"] = field.label

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, View

from accounts.models import FriendShip, User
from tweets.models import Like, Tweet

from .forms import LoginForm, SignUpForm


class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)

    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password)
        if user is not None:
            login(self.request, user)
            return response
        else:
            return redirect("welcome:top")


class LoginView(views.LoginView):
    template_name = "accounts/login.html"
    form_class = LoginForm


class LogoutView(views.LogoutView):
    pass


class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    context_object_name = "profile_user"
    template_name = "accounts/profile.html"
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tweets"] = Tweet.objects.select_related("user").filter(user=self.object).order_by("-created_at").all()
        context["is_following"] = FriendShip.objects.filter(following=self.request.user, follower=self.object).exists()
        context["following_numbers"] = FriendShip.objects.filter(following=self.object).count()
        context["followers_numbers"] = FriendShip.objects.filter(follower=self.object).count()
        context["liked_tweets"] = Like.objects.filter(user=self.request.user).values_list("tweet", flat=True)
        return context


class FollowingListView(LoginRequiredMixin, ListView):
    model = User
    context_object_name = "folloing_list"
    template_name = "accounts/following_list.html"

    def get_queryset(self):
        self.user = get_object_or_404(User, username=self.kwargs["username"])
        return self.user.followers.all().order_by("-date_joined")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["target_user"] = self.user
        return context


class FollowerListView(LoginRequiredMixin, ListView):
    model = User
    context_object_name = "follower_list"
    template_name = "accounts/follower_list.html"

    def get_queryset(self):
        self.user = get_object_or_404(User, username=self.kwargs["username"])
        return self.user.followings.all().order_by("-date_joined")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["target_user"] = self.user
        return context


class FollowView(LoginRequiredMixin, View):
    def post(self, *args, **kwargs):
        user = get_object_or_404(User, username=self.kwargs["username"])

        if user == self.request.user:
            messages.add_message(self.request, messages.ERROR, "自分自身をフォローすることはできません")
            return redirect("tweets:home")

        if self.request.user.followers.filter(username=user.username).exists():
            messages.add_message(self.request, messages.WARNING, "すでにフォローしています。")
            return redirect("tweets:home")

        self.request.user.followers.add(user)
        messages.add_message(self.request, messages.SUCCESS, "フォローしました。")
        return redirect("tweets:home")


class UnFollowView(LoginRequiredMixin, View):
    def post(self, *args, **kwargs):
        user = get_object_or_404(User, username=self.kwargs["username"])

        if user == self.request.user:
            messages.add_message(self.request, messages.ERROR, "自分自身をフォロー解除することはできません。")
            return redirect("tweets:home")

        if not self.request.user.followers.filter(username=user.username).exists():
            messages.add_message(self.request, messages.ERROR, "フォローしていません。")
            return redirect("tweets:home")

        self.request.user.followers.remove(user)
        messages.add_message(self.request, messages.SUCCESS, "フォローを解除しました。")
        return redirect("tweets:home")

templates/accounts/follower_list.html
{% extends 'base.html' %}

{% block title %}Follower List{% endblock %}

{% block content %}
<h1>{{ target_user }} 's Follower List</h1>

<div class="followier-list">
    {% for object in object_list %}
    <a href="{% url 'accounts:user_profile' user.username %}">{{ object.username }}</a>

    {% empty %}
    <p>フォローワーがいません。</p>
        
    {% endfor %}
</div>
{% endblock %}

templates/accounts/following_list.html
{% extends 'base.html' %}

{% block title %}Following List{% endblock %}

{% block content %}
<h1>{{ target_user }} 's Following List</h1>

<div class="following-list">
    {% for object in object_list %}
    <a href="{% url 'accounts:user_profile' user.username %}">{{ object.username }}</a>

    {% empty %}
    <p>誰もフォローしていません。</p>
        
    {% endfor %}
</div>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}LOGIN{% endblock %}

{% block content %}
<div id="login" class="login">
    <form method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
        {{ field }}
        {{ field.errors }}
        <hr>
        {% endfor %}
        {% csrf_token %}
        <button type = "submit">ログイン</button>
    </form>
</div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% block title %}プロフィール{% endblock %}
{% block h1 %}プロフィール{% endblock %}

{% block content %}
<div class="profile">
    {% if profile_user.username == user.username %}
    <h1>My profile</h1>

    {% else %}
    <h1>{{ profile_user }} 's profile</h1>
    <div class="follow">
        {% if is_following %}
        <form action="{% url 'accounts:unfollow' profile_user.username %}" method="POST">
            {% csrf_token %}
            <button>Unfollow</button>
        </form>
        {% else %}
        <form action="{% url 'accounts:follow' profile_user.username %}" method="POST">
            {% csrf_token %}
            <button>Follow</button>
        </form>

        {% endif %}
        
    {% endif %}

    <a href="{% url 'accounts:following_list' profile_user.username %}">フォロー数:{{ following_numbers }}人</a>
    <a href="{% url 'accounts:follower_list' profile_user.username %}">フォローワー数:{{ followers_numbers }}人</a>

    <h2>過去のツイート</h2>

        {% for tweet in tweets %}
        [ツイート時間] {{ tweet.created_at }}
        <br>
        [ツイート内容] {{ tweet.content }}
        <br>
        <a href="{% url 'tweets:detail' tweet.pk %}">詳細</a>
        <br>
        {% include 'tweets/like.html' %}
        <br>
        {% empty %}
        <p>ツイートがまだありません。</p>
        
    {% endfor %}
</div>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<div id="signup" class="signup">
    <form method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <button type = "submit">登録</button>
    </form>
</div>
{% endblock %}