accounts/urls.py
# from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"
urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

tweets/models.py
from django.conf import settings
from django.db import models


class Tweet(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)

    @property
    def liked_count(self):
        return self.likes.count()

    def __str__(self):
        return self.content


class Like(models.Model):
    tweet = models.ForeignKey(Tweet, on_delete=models.CASCADE, related_name="likes")
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="likes")

    class Meta:
        constraints = [models.UniqueConstraint(fields=["tweet", "user"], name="unique_like")]

tweets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, ListView, View

from tweets.models import Like, Tweet


class HomeView(LoginRequiredMixin, ListView):
    model = Tweet
    context_object_name = "tweets"
    template_name = "tweets/home.html"
    ordering = "-created_at"
    queryset = Tweet.objects.prefetch_related("likes").select_related("user").all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liked_tweets"] = Like.objects.filter(user=self.request.user).values_list("tweet", flat=True)
        return context


class TweetCreateView(LoginRequiredMixin, CreateView):
    model = Tweet
    fields = ["content"]
    template_name = "tweets/create.html"
    success_url = reverse_lazy("tweets:home")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class TweetDetailView(LoginRequiredMixin, DetailView):
    model = Tweet
    context_object_name = "tweet"
    template_name = "tweets/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["liked_tweets"] = (
            Like.objects.select_related("user").filter(user=self.request.user).values_list("tweet", flat=True)
        )
        return context


class TweetDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Tweet
    context_object_name = "tweet_delete"
    template_name = "tweets/delete.html"
    success_url = reverse_lazy("tweets:home")

    def test_func(self):
        tweet = self.get_object()
        return self.request.user == tweet.user


class LikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        tweet = get_object_or_404(Tweet, pk=kwargs["pk"])
        Like.objects.get_or_create(user=self.request.user, tweet=tweet)
        context = {
            "liked_count": tweet.liked_count,
            "tweet_id": tweet.id,
            "is_liked": True,
        }
        return JsonResponse(context)


class UnlikeView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        tweet = get_object_or_404(Tweet, pk=kwargs["pk"])
        Like.objects.filter(user=self.request.user, tweet=tweet).delete()
        context = {
            "liked_count": tweet.liked_count,
            "tweet_id": tweet.id,
            "is_liked": False,
        }
        return JsonResponse(context)

templates/tweets/create.html
{% extends 'base.html' %}

{% block title %}Tweet{% endblock %}

{% block content %}
<div class="create">
    <h1>Tweet!</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">tweet!</button>
    </form>
</div>
{% endblock content %}

templates/tweets/delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock %}

{% block content %}
<div class="delete">
    <p>[作成者]{{ tweet.user }}</p>
    <p<[ツイート時間] {{ tweet.created_at }}</p>
    <p>[ツイート内容] {{ tweet.content }}</p>
    <form method="post">
        {% csrf_token %}
        <p>ツイート内容を削除いたしますか。</p>
        <button type="submit">delete</button>
    </form>
</div>
{% endblock content %}

templates/tweets/detail.html
{% extends 'base.html' %}

{% block title %}Detail{% endblock %}

{% block content %}
<div class="detail">
    <a href="{% url 'accounts:user_profile' tweet.user %}">{{tweet.user}}</a>
    <p>{{ tweet.content }}</p>
    <p>{{ tweet.created_at }}</p>
    {% include 'tweets/like.html' %}

    {% if tweet.user == request.user %}
    <a href="{% url 'tweets:delete' tweet.pk %}">削除</a>
    {% endif%}
</div>
{% endblock content %}

templates/tweets/home.html
{% extends 'base.html' %}

{% block title %}HomePage{% endblock %}

{% block content %}
<div class="homepage">
    <h1>HomePage</h1>
    <a href="{% url 'tweets:create' %}">ツイートする</a>
    
    {% for tweet in tweets %}
    <div class="tweet-contents">
        <a href="{% url 'accounts:user_profile' tweet.user %}">[投稿者] {{ tweet.user }}</a>
        <br>
        [ツイート時間] {{ tweet.created_at }}
        <br>
        [ツイート内容] {{ tweet.content }}
        <br>
        <a class="detail" href="{% url 'tweets:detail' tweet.pk %}">詳細</a>
        <br>
        {% include 'tweets/like.html' %}
    </div>
    
    {% empty %}
    <p>ツイートはありません</p>

    {% endfor %}

</div>
{% endblock %}

templates/tweets/like.html
{% if tweet.id in liked_tweets %}
<button id="tweet_{{tweet.id}}" onclick="likeAction(tweet_{{tweet.id}})"
    data-url="{% url 'tweets:unlike' tweet.id %}">いいね解除</button>

{% else %}
<button id="tweet_{{tweet.id}}" onclick="likeAction(tweet_{{tweet.id}})"
    data-url="{% url 'tweets:like' tweet.id %}">いいね</button>
    
{% endif %}

いいね数:<span name="count_{{tweet.id}}" class="count">{{ tweet.liked_count }}</span>