accounts/urls.py
# from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    path("<str:username>/follow/", views.FollowView.as_view(), name="follow"),
    path("<str:username>/unfollow/", views.UnFollowView.as_view(), name="unfollow"),
    path("<str:username>/following_list/", views.FollowingListView.as_view(), name="following_list"),
    path("<str:username>/follower_list/", views.FollowerListView.as_view(), name="follower_list"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"
urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    path("create/", views.TweetCreateView.as_view(), name="create"),
    path("<int:pk>/", views.TweetDetailView.as_view(), name="detail"),
    path("<int:pk>/delete/", views.TweetDeleteView.as_view(), name="delete"),
    path("<int:pk>/like/", views.LikeView.as_view(), name="like"),
    path("<int:pk>/unlike/", views.UnlikeView.as_view(), name="unlike"),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>
  <header>
    {% if user.is_authenticated %}
      <div class="member">
        <a type="button" href="{% url 'accounts:user_profile' user.username %}">User_Profile</a>
        <br>
        <a type="button" href="{% url 'tweets:home' %}">Twitter Clone</a>
        <br>
        <form action="{% url 'accounts:logout' %}" method="POST">
          {% csrf_token %}
          <button type="submit">ログアウト</button>
        </form>
      </div>
    {% else %}
      <div class="non-menber">
        <a type="button" href="{% url 'accounts:login' %}">ログイン</a>
        <br>
        <a type="button" href="{% url 'accounts:signup' %}">登録</a>
      </div>
    {% endif %}

    {% if messages %}
    <div>
      {% for message in messages %}
      <p>{{ message }}</p>
      {% endfor %}
    </div>
    {% endif %}
  </header>

  <main>
    <h1>
      {% block h1 %}{% endblock %}
    </h1>
      {% block content %}{% endblock %}
  </mian>

  <footer>
  
  </footer>

  <script src="{% static 'js/like.js' %}"></script>
</body>

</html>